### ISSUE TITLE
[1.20.1] "Invalid Player Data"-error when loading into single-player world

### ISSUE THREAD

**Issue by Taschenmogul** [Abbie5/emi-ores#33]
Just for your interest. I checked out this mod and decided that it's not important for me anyway, so I just removed it and everything is fine again.
However I'll mention the issue here quickly, for the record:

Having EMI Ores installed made me unable to join a world, even a newly-created one, with the on-screen message being "Invalid Player Data". I had just recently adjusted ore spawning using the data pack functionality of KubeJS, and without EMI Ores it worked without issue.
Forgive me for not posting the whole log, but the relevant error message given was this:

```
[Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Trying to access unbound value 'ResourceKey[minecraft:worldgen/biome / minecraft:]' from registry net.minecraft.core.MappedRegistry$1@323305d3
	Index: 3
	Listeners:
		0: NORMAL
		1: ASM: org.embeddedt.modernfix.forge.init.ModernFixForge@1c2e3b7d onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		2: ASM: class dev.xkmc.l2library.init.events.GeneralEventHandler onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		3: net.minecraftforge.eventbus.EventBus$$Lambda$1651/0x00000285a2790438@770b7932
		4: ASM: class dan200.computercraft.shared.ForgeCommonHooks onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		5: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onDataSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		6: ASM: class net.mehvahdjukaar.moonlight.forge.MoonlightForge onDataSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		7: ASM: class com.gregtechceu.gtceu.forge.ForgeCommonEventListener onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		8: ASM: class com.simibubi.create.foundation.events.CommonEvents onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1651/0x00000285a2790438@2a43aab2
		10: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@659141ff onDatapackSync(Lnet/minecraftforge/event/OnDatapackSyncEvent;)V
		11: net.minecraftforge.eventbus.EventBus$$Lambda$1651/0x00000285a2790438@3c510ff2
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/biome / minecraft:]' from registry net.minecraft.core.MappedRegistry$1@323305d3
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.core.Holder$Reference.m_203334_(Holder.java:147)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$9.transformEntry(Maps.java:2117)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$12.getValue(Maps.java:2165)
	at TRANSFORMER/emi_ores@1.0+1.20.1+forge/cc.abbie.emi_ores.networking.FeaturesSender.lambda$onSyncDataPackContents$4(FeaturesSender.java:52)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$IteratorBasedAbstractMap.forEachEntry(Maps.java:3878)
	at MC-BOOTSTRAP/com.google.common@31.1-jre/com.google.common.collect.Maps$IteratorBasedAbstractMap$1.forEach(Maps.java:3872)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
	at TRANSFORMER/emi_ores@1.0+1.20.1+forge/cc.abbie.emi_ores.networking.FeaturesSender.onSyncDataPackContents(FeaturesSender.java:51)
	at TRANSFORMER/emi_ores@1.0+1.20.1+forge/cc.abbie.emi_ores.forge.EmiOresForge.lambda$onDatapackSync$3(EmiOresForge.java:25)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at TRANSFORMER/emi_ores@1.0+1.20.1+forge/cc.abbie.emi_ores.forge.EmiOresForge.onDatapackSync(EmiOresForge.java:25)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)

[Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/biome / minecraft:]' from registry net.minecraft.core.MappedRegistry$1@323305d3
	at net.minecraft.core.Holder$Reference.m_203334_(Holder.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at com.google.common.collect.Maps$9.transformEntry(Maps.java:2117) ~[guava-31.1-jre.jar%2374!/:?]
	at com.google.common.collect.Maps$12.getValue(Maps.java:2165) ~[guava-31.1-jre.jar%2374!/:?]
	at cc.abbie.emi_ores.networking.FeaturesSender.lambda$onSyncDataPackContents$4(FeaturesSender.java:52) ~[emi_ores-1.0+1.20.1+forge.jar%23439!/:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at com.google.common.collect.Maps$IteratorBasedAbstractMap.forEachEntry(Maps.java:3878) ~[guava-31.1-jre.jar%2374!/:?]
	at com.google.common.collect.Maps$IteratorBasedAbstractMap$1.forEach(Maps.java:3872) ~[guava-31.1-jre.jar%2374!/:?]
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092) ~[?:?]
	at cc.abbie.emi_ores.networking.FeaturesSender.onSyncDataPackContents(FeaturesSender.java:51) ~[emi_ores-1.0+1.20.1+forge.jar%23439!/:?]
	at cc.abbie.emi_ores.forge.EmiOresForge.lambda$onDatapackSync$3(EmiOresForge.java:25) ~[emi_ores-1.0+1.20.1+forge.jar%23439!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at cc.abbie.emi_ores.forge.EmiOresForge.onDatapackSync(EmiOresForge.java:25) ~[emi_ores-1.0+1.20.1+forge.jar%23439!/:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23109!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23109!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:188) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:139) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:126) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23582!/:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by Abbie5** [comment]
Thanks for reporting this, it seems that somehow a biome is being registered with an empty id? Not sure how that happened. Please send the full log (using a paste site such as https://mclo.gs/ is fine) so that I can troubleshoot further.

**Comment by Taschenmogul** [comment]
Sorry, that's too much effort for me, the respective log is already burried under lots of newer ones now, since I just moved on with tweaking the mod pack.
Potentially what you might be looking for could be TerraBlender's "terrablender:deferred_placeholder" biome or Blueprint's "blueprint:original_source_marker" though.
Dimensional Doors also implements biomes that don't carry ore, but these are actually generated in the game, while the former two are not, from what I understand.

**Comment by Legotier** [comment]
I have the same problem, here's my full log: https://mclo.gs/mrFdwpK

**Comment by Abbie5** [comment]
@Legotier your issue is caused by "Treeplacer - Terralith Addon", please report it to them.

**Comment by Legotier** [comment]
@Abbie5 Alright, I didn't get that from the logs. Thanks for your help!

**Comment by castilio20** [comment]
@Abbie5 same type of error https://mclo.gs/Ag0Q5R3 and i dont have treeplacer

**Comment by pafeuu** [comment]
Hey I have the same problems but I dont have the mods mentioned above, could you tell me what mod could be causing this?
https://mclo.gs/6OKzN0E
